### ISSUE TITLE
plot_effects.R needs modularization

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#22]
This file is extremely difficult to understand. It is a ~800 line function with god knows how many nested if statements. It'll need some major cleanup if any more plotting functionality needs to be added.

**Comment by rkingdc** [comment]
This function is an edited version of the plot.eff method out of John Fox's effects package that is loaded in the server.r file. I added several arguments to make the function more flexible for my specific needs on a paper I was writing some time ago. The differences from his function are subtle and probably unnecessary. In fact he incorporated a couple of my suggestions into the most recent version of effects, so this version is only slightly different. 

So toss it. I don't think it is even used when making the effects plot anyway. I'm I remember correctly, when I'm constructing the plots, I call plot() on the "eff" object (object created by the "Effects" function) rather than "my" function "plot_effects". I can verify this later.

**Comment by moorepants** [comment]
You gotta be kidding. I just started reading all the code so I know what does what. In the process I started cleaning up the style so that things are easier to read. I didn't check to see if the plot_effects.R file was used elsewhere, I just assumed it was. I probably spent 2+ hours reformatting it so I could figure out what the hell it was doing.

**Comment by moorepants** [comment]
Also, I feel sorry for John Fox if that is what his code looks like :smile: .

**Comment by moorepants** [comment]
I see your note in server.R now. I should have read that more closely.

**Comment by moorepants** [comment]
I apologize for the above statement, that probably was bashing your code too. It was just a quick reaction to me feeling like I wasted my time editing that file.

**Comment by rkingdc** [comment]
Oh god I am so sorry. I should have removed that a long time ago. 

And don't hate on john fox. The fact that he was able to write that wrapper for lattice plots is incredible in my opinion. Lattice produces awesome plots, but making really complicated stuff look awesome is a pain in the ass. That function accepts model objects from the base stats package, lme4 mixed models, nlme mixed models (both linear and generalized), ordinal mutlinomial logistic models from the ordinal package, and latent class models from poLCA. And those are just the packages with official support. That package works with any model that works with the various generic model parameter extraction functions. 

I'm surprised it looks as good as it does.

**Comment by moorepants** [comment]
I'm sure it does a lot. I'm just a stickler for readability of code, as code is read much much more often than it is written.

**Comment by rkingdc** [comment]
fair enough.

**Comment by moorepants** [comment]
BTW, is any other source in this repository from some one else? If so, we need to respect the licenses they are released under. That code of John's is GPL and I just changed the license to BSD, so that code needs to be removed or I need to revert the license.

**Comment by rkingdc** [comment]
It's all either stuff I wrote all on my own or from the various packages​.

**Comment by moorepants** [comment]
But is any of the code besides `plot_effects.R` copied from elsewhere (and/or modified)?

**Comment by rkingdc** [comment]
Nothing copy and pasted. Just stuff based on examples from stack overflow and gists.

**Comment by moorepants** [comment]
Ok, sweet. I may nuke the `plot_effects.R` if it isn't needed.

**Comment by rkingdc** [comment]
​I support that​
