### ISSUE TITLE
Reloading the browser kills the app

### ISSUE THREAD

**Issue by moorepants** [ucd-ipo/aip-analysis#27]
To reproduce, use `runApp('inst/app')` to start the server and the refresh the browser window. The server disconnects, R unblocks, and there are no error messages.

**Comment by moorepants** [comment]
This says that live reloading should work: http://shiny.rstudio.com/articles/running.html

**Comment by moorepants** [comment]
If I launch the app like so:

```
> library('AIP')
> AIP()

Listening on http://127.0.0.1:6330
NULL
> 
```

It does the same thing and prints `NULL` to the screen.

**Comment by moorepants** [comment]
@ikkyle Do you have any idea why this fails?

**Comment by rkingdc** [comment]
Yeah. At the bottom of the server.R file, there is code to end the session when the browser session ends.

```
  session$onSessionEnded(function() {
    stopApp()
  })
```

This is there because otherwise the r session will never end when the app is run non-interactively. You can remove that code and the session should persist, but you'll have to figure out another way to exit the R session when the user is finished.

**Comment by moorepants** [comment]
Thanks, I hadn't gotten all the way through the server.R file :) I just want to turn that off for debugging purposes so I can live reload the app.

But I'm not sure that the is the behavior you'd want for end users either. In general, a browser based app shouldn't shutdown on reload, it should persist or reset or something.

What do you mean "when the app is run non-interactively"?

**Comment by rkingdc** [comment]
When you are running and developing the app locally, you have an interactive R session open. So you end the R session when you close R. I don't know how you guys are planning on deploying the app now, but when I had it set up to run on a flash drive, the user would click a visual basic script that would run an R batch mode session. This opens a browser and allows the user to use the app without every having to open R. Without the `onSessionEnded` bit, the R session will persist even after the browser is closed. And since R is running in batch mode, the user would have to kill the rsession via command line or task manager.

**Comment by moorepants** [comment]
Got it. I'll figure out some way to have both "modes" available. For now, I just need to be able to quickly debug and live reloading helps a ton. I'll open an issue for this and address it later.
