### ISSUE TITLE
Can't load AIP app

### ISSUE THREAD

**Issue by msimmond** [ucd-ipo/aip-analysis#88]
ERROR: â€œshinyâ€ version 0.11.1 cannot be unloaded.

**Comment by moorepants** [comment]
Please describe exactly what you've tried and when the error appeared, i.e. all steps.

Things to check:
- All of the exact dependencies are installed (versions have to match what we require, including R). Make sure the versions match the numbers in the [DESCRIPTION](https://github.com/ucd-ipo/aip-analysis/blob/master/DESCRIPTION) file (it may not work with versions released since we've last run the app).
- How are you installing the app? Using devtools or install.packages or other?
- Does the library load correctly?

**Comment by rkingdc** [comment]
The app depends on shiny package version >= 0.12. Do you have an older version installed?

**Comment by msimmond** [comment]
```
'> devtools::install_github('ucd-ipo/aip-analysis')
Downloading github repo ucd-ipo/aip-analysis@master
Installing AIP
Installing dependencies for AIP:
shiny
also installing the dependency ‘httpuv’

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/httpuv_1.3.3.tgz'
Content type 'application/x-gzip' length 843657 bytes (823 KB)
opened URL
'==================================================
downloaded 823 KB

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/shiny_0.12.2.tgz'
Content type 'application/x-gzip' length 1816483 bytes (1.7 MB)
opened URL
'==================================================
downloaded 1.7 MB


The downloaded binary packages are in
    /var/folders/dt/pqp7k72x4854hpxckpzj_wh80000gn/T//RtmpJVwSQ9/downloaded_packages
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/dt/pqp7k72x4854hpxckpzj_wh80000gn/T/RtmpJVwSQ9/devtools85252859e0a/ucd-ipo-aip-analysis-13ad7e7'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 

'* installing *source* package ‘AIP’ ...
'** R
'** inst
'** preparing package for lazy loading
'** help
No man pages found in package  ‘AIP’ 
'*** installing help indices
'** building package indices
'** testing if installed package can be loaded
'* DONE (AIP)
'> library('AIP')
'> AIP()
Loading required package: shiny
Error in unloadNamespace(package) : 
  namespace ‘shiny’ is imported by ‘HH’ so cannot be unloaded
Failed with error:  ‘“shiny” version 0.11.1 cannot be unloaded.’

Listening on http://127.0.0.1:3532
Error in unloadNamespace(package) : 
  namespace ‘shiny’ is imported by ‘HH’ so cannot be unloaded
Error in library("shiny") : “shiny” version 0.11.1 cannot be unloaded.
Error in unloadNamespace(package) : 
  namespace ‘shiny’ is imported by ‘HH’ so cannot be unloaded
Error in library("shiny") : “shiny” version 0.11.1 cannot be unloaded.
Error in unloadNamespace(package) : 
  namespace ‘shiny’ is imported by ‘HH’ so cannot be unloaded
Error in library("shiny") : “shiny” version 0.11.1 cannot be unloaded.
```

**Comment by msimmond** [comment]
The output above is from R Studio Console (Version 0.98.1103).
I was following the instructions from the "installation and usage" on home page of ucd-ipo/aip-analysis.

**Comment by msimmond** [comment]
If I follow the link https://moorepants.shinyapps.io/aftsp, it works.

**Comment by rkingdc** [comment]
I can't replicate because I'm getting a different error due to a bug in `devtools` I think (see [#89](https://github.com/ucd-ipo/aip-analysis/issues/89)). Its sounds like `HH` and `shiny` have conflicting namespaces. We could try loading the shiny package last and see if that fixes the issue. 

But first, type `sessionInfo()` at your console and paste the output below. 

Next, can you restart R and try again loading `AIP` without `HH` loaded (if it was already loaded?). I don't think HH is a dependency of anything in `AIP`, but I could be wrong.

If that doesn't work, try navigating to the source code for the AIP analysis and in the app/sever.R file, change the code such that packages that don't depend on shiny are loaded first. So in server.R, change the order packages are loaded to: 

```
library('agricolae')
library('car')  
library('Rmisc') 
library('ggplot2') 
library('knitr')
library('shiny')
library('shinyBS')
library('shinyAce')
```

If `HH` is a dependency of the `AIP` package and it has a conflicting namespace with shiny, shiny will be loaded after and will take precedence.

**Comment by rkingdc** [comment]
Quick tip: As long as you have all the dependencies installed, you can run the app without installing the whole package using:

``` r
shiny::runGitHub('ucd-ipo/aip-analysis', subdir = 'inst/app')
```

**Comment by moorepants** [comment]
HH is not a dependency of the app (we used it in some of the examples).

**Comment by rkingdc** [comment]
@msimmond, did you ever get this figured out?
