### ISSUE TITLE
post-hoc analysis error `missing value where TRUE/FALSE needed`

### ISSUE THREAD

**Issue by rkingdc** [ucd-ipo/aip-analysis#91]
Using the following parameters,

Data: split-plot design
Experimental Design: Split-Plot RCBD
DV: yield
IVs:
main plot treatment: A
sub plot treatment: plot
blocking factor variable: block
Transformations: None

Running Post-hoc tests, I get the error 

```
Error in if (interaction.p.value < alpha) { : 
  missing value where TRUE/FALSE needed
```

in the console when I click "Run post hoc analysis".

**Comment by msimmond** [comment]
See updated code in pull request for split_plot_rcbd.R

**Comment by msimmond** [comment]
Even with the new code merged, I am still getting that error when running post-hoc tests for a split-plot RCBD - however, it works when there's a significant interaction. The error happens when there is no significant interaction but the main-plot or sub-plot are significant. In that case, there should be LSD tests on the significant factors, and bar graphs made for both factors regardless of significance (if not sig, use a letter 'a' for all bars).

**Comment by rkingdc** [comment]
fixed a while back.
